import {Inter} from 'next/font/google';

import {Sidebar} from '@/components/Sidebar';

import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-surface dark:bg-dark-surface dark:text-dark-text`}
      >
        <div className="flex flex-row h-screen">
          <Sidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
