import {Inter, Albert_Sans} from 'next/font/google';

import {Sidebar, Topbar} from '@/components';

import './globals.css';

const font = Albert_Sans({
  display: 'fallback',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${font.className} bg-surface dark:bg-dark-surface dark:text-dark-text`}
      >
        {children}
      </body>
    </html>
  );
}
