// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Logo: typeof import('./components/Logo.vue')['default']
    PixelarticonsPower: typeof import('~icons/pixelarticons/power')['default']
    PixelarticonsZap: typeof import('~icons/pixelarticons/zap')['default']
  }
}
